
easy_phrases = [
    "Believe in yourself and stay strong",
    "Small steps lead to big achievements",
    "Your mindset shapes your future path",
    "Hard work and patience bring success",
    "Dream big and take action every day",
    "Success comes from daily small wins",
    "Stay focused and trust the process",
    "Every challenge helps you grow wiser",
    "Your habits define your future self",
    "Keep pushing forward, never give up",
    "Effort and discipline create results",
    "Opportunities grow when you take action",
    "Stay committed to your personal growth",
    "The road to success is never easy",
    "Great things take time, be patient",
    "Your daily actions shape your future",
    "Nothing changes if nothing changes",
    "Consistency is the key to success",
    "Failure is just a lesson in disguise",
    "Work hard, dream big, stay humble",
    "The best investment is in yourself",
    "Push past limits and grow stronger",
    "Your potential is greater than fear",
    "Discipline is the bridge to success",
    "Keep learning, keep improving daily",
    "Every effort counts towards success",
    "You are one step away from progress",
    "Growth starts outside the comfort zone",
    "Your journey is unique, embrace it",
    "Success comes to those who persist",
    "Turn obstacles into stepping stones",
    "Trust yourself and take bold steps",
    "Every day is a chance to improve",
    "Stay positive and work towards goals",
    "Progress happens when you take action",
    "Your future depends on your choices",
    "Keep going even when it gets tough",
    "Big goals require daily small efforts",
    "Your actions today create tomorrow",
    "Challenges build resilience and strength",
    "Believe, act, and success will follow",
    "Stay patient, results take time",
    "Great things happen outside comfort zones",
    "Your focus determines your reality",
    "Success follows those who work hard",
    "Small efforts lead to major results",
    "Never stop improving and growing",
    "Your growth starts with one decision",
    "Take risks, learn, and keep moving",
    "The secret to success is persistence",
    "Stay disciplined, success will come",
    "Hustle today for a better tomorrow",
    "Your dedication defines your success",
    "Trust the process and keep going",
    "Hard work today pays off tomorrow",
    "Your journey is yours, own it",
    "Struggles today build strength tomorrow",
    "Every step forward is progress made",
    "Take action and create opportunities",
    "Success is built with daily effort",
    "Stay committed to your daily goals",
    "You are stronger than your doubts",
    "Turn failures into valuable lessons",
    "Your consistency determines your future",
    "Effort and time create great results",
    "Success is earned, not given freely",
    "Believe, work, and achieve greatness",
    "Big dreams require strong dedication",
    "You control your progress and growth",
    "Make today better than yesterday",
    "The best way forward is to start",
    "You are capable of amazing things",
    "Small wins create big achievements",
    "Discipline turns dreams into reality",
    "Your habits shape your future life",
    "Success is a result of preparation",
    "Push forward and trust your journey",
    "Your dreams need effort and belief",
    "The key to success is never quitting",
    "Keep working, your time will come",
    "A strong mindset builds strong results",
    "Stay dedicated and trust your process",
    "You become what you repeatedly do",
    "Keep striving, keep believing, win",
    "Hard work beats talent every time",
    "Your daily actions define your future",
    "Success happens when you stay consistent",
    "Small actions lead to great change",
    "Dream, plan, and execute daily steps",
    "Your effort today builds tomorrow's success",
    "Every day is an opportunity to grow",
    "Stay motivated and never lose focus",
    "Commitment is the secret to success",
    "Success is built through daily habits",
    "Your journey requires patience and action",
    "Keep showing up, results will follow",
    "The path to success is daily effort",
    "You have everything it takes to win",
    "Challenges make you stronger and wiser",
    "Be relentless in pursuit of your goals"
]


medium_phrases = [
    "Hard work and patience lead to great success in life",
    "Every challenge is a chance to grow stronger and wiser",
    "Stay focused and always trust your unique life journey",
    "Small steps today will bring massive results tomorrow",
    "Believe in yourself and never stop learning and growing",
    "Your mindset shapes the future and the life you create",
    "Success comes from consistent effort and determination",
    "Keep going, even when the road ahead seems really tough",
    "Discipline and passion fuel the path to long-term success",
    "Dreams become real with action, courage, and persistence",
    "Opportunities grow when you take action and stay prepared",
    "Failures are lessons that help guide us to better choices",
    "The key to success is consistency, patience, and focus",
    "Growth happens outside of your comfort zone, always",
    "Stay committed to your goals, even when progress is slow",
    "Hardships shape strong minds and build unshakable character",
    "Embrace every challenge, for it helps you become stronger",
    "Your daily habits determine the quality of your future",
    "Small improvements each day lead to massive achievements",
    "The road to success is built with discipline and effort",
    "Believe in your dreams, work hard, and never give up",
    "The best investment you can make is in yourself today",
    "Your mindset determines the life you create and live",
    "Courage is the power to move forward despite any fear",
    "Success starts when you step outside of your comfort zone",
    "Growth requires patience, consistency, and daily action",
    "Turn obstacles into stepping stones to your success",
    "The only way to fail is by giving up on your goals",
    "Your attitude determines how high you can truly rise",
    "Nothing great comes easy; effort always brings rewards",
    "Your success is a direct reflection of your discipline",
    "Great things take time, so trust the process always",
    "The journey is just as important as the destination",
    "Every day is a new chance to improve and move forward",
    "Don't wait for opportunities; create them yourself",
    "Dream big, start small, but take action right away",
    "Your potential is unlimited when you truly believe",
    "Every effort you make today will pay off in the future",
    "If you want success, be willing to work for it daily",
    "Small steps taken consistently lead to major success",
    "You are capable of more than you even realize today",
    "Challenges help you grow into the best version of you",
    "The future belongs to those who take action right now",
    "Keep learning, keep improving, and stay persistent",
    "Hard work beats talent when talent refuses to work",
    "Success happens when preparation meets opportunity",
    "Focus on progress, not perfection, and keep moving",
    "Discipline is doing what needs to be done every day",
    "Growth is uncomfortable, but it's always worth it",
    "Stay determined, even when the journey seems tough",
    "Your actions today shape the results of tomorrow",
    "The more effort you put in, the greater the reward",
    "Never fear failure; it's just another way to learn",
    "Consistency and patience are the keys to success",
    "You are one decision away from a completely new life",
    "The best way to predict the future is to create it",
    "Effort, patience, and strategy will bring success",
    "Your habits today define your success for tomorrow",
    "Great achievements come from small daily progress",
    "If you never give up, you can never truly fail",
    "Trust yourself and stay focused on your goals",
    "Big dreams require discipline, action, and courage",
    "The road to success is paved with hard work daily",
    "Your struggles today will be your strengths tomorrow",
    "Growth comes from pushing beyond your comfort zone",
    "The best version of you is built one day at a time",
    "Confidence comes from consistent effort and learning",
    "The secret to success is to keep moving forward",
    "The harder you work, the luckier you will become",
    "Success is a journey, not a destination to reach",
    "Your efforts today create the results of tomorrow",
    "Results come from daily effort, not occasional work",
    "No dream is too big if you're willing to work for it",
    "Your time is valuable, so invest it wisely every day",
    "Setbacks are just setups for future comebacks in life",
    "The more you push forward, the stronger you become",
    "Stay patient, stay focused, and never lose hope",
    "The best results come from long-term consistent work",
    "Nothing is impossible with the right mindset and effort",
    "Perseverance is the bridge between goals and success",
    "The only way to make progress is by taking action",
    "Success is built on persistence and continuous learning",
    "A strong mindset leads to an unstoppable future ahead",
    "Your vision becomes reality with action and dedication",
    "Growth comes from consistent effort, not overnight wins",
    "If you stay disciplined, success will always find you",
    "The more you learn, the more doors will open for you",
    "Trust the process and enjoy the journey to success",
    "Greatness is achieved by making small daily choices",
    "Discipline and patience lead to long-lasting success",
    "Everything you need to succeed is already inside you",
    "Believe in your abilities and never doubt yourself",
    "Big goals require daily action and unwavering focus",
    "The more consistent you are, the better the results",
    "Hard work today leads to a brighter future tomorrow",
    "Your strength is built through life's toughest battles",
    "Embrace change, adapt quickly, and keep moving forward",
    "Every setback is a setup for something even greater",
    "Stay positive, stay productive, and stay persistent"
]

hard_phrases = [
    "Success is built on consistent effort, patience, and resilience, even when progress feels slow",
    "Your dreams become reality when you take action, stay focused, and refuse to give up",
    "The journey to success is not always easy, but persistence and hard work will lead you there",
    "Every small step you take today brings you closer to the future you've always dreamed of",
    "Discipline and dedication are the keys that unlock the doors to long-term success and growth",
    "Opportunities don't just appear; they are created through preparation, effort, and persistence",
    "The only way to guarantee failure is to quit, so keep pushing forward no matter what happens",
    "Your mindset is the foundation of your success; believe in yourself and take consistent action",
    "Big achievements are the result of small, smart decisions made consistently over time",
    "Success is not about luck; it's about patience, discipline, and the courage to keep going",
    "Your goals will only be achieved if you are willing to commit to daily progress and growth",
    "Hard work today will pay off in ways you can't even imagine in the future, so stay dedicated",
    "The difference between success and failure is often just the ability to keep going despite setbacks",
    "Challenges and failures are simply stepping stones toward the person you are meant to become",
    "The road to success may be difficult, but every lesson along the way makes you stronger",
    "You don't have to be perfect to succeed; you just have to be willing to keep improving daily",
    "Effort and patience will always be rewarded, even if the results take time to show up",
    "Success doesn't come from what you do occasionally but from what you do consistently",
    "Growth happens when you step outside your comfort zone and challenge yourself every day",
    "Your future depends on the actions you take today, so choose wisely and stay consistent",
    "The best way to predict your future is to take action and create it yourself",
    "Small, intentional actions every day will lead to significant achievements in the future",
    "Your progress may be slow, but every step forward is still a step in the right direction",
    "Never let temporary struggles convince you to give up on your long-term dreams",
    "Every challenge you overcome makes you stronger, wiser, and more prepared for the future",
    "Your habits today shape your success tomorrow, so build habits that move you forward",
    "Results come to those who are patient, consistent, and willing to learn from every experience",
    "If you want to change your life, start by changing the small choices you make every day",
    "Your dreams require effort, persistence, and a strong belief that you are capable of achieving them",
    "The best investment you can ever make is in yourself, your skills, and your personal growth",
    "Success is not an overnight event but the result of countless small efforts over time",
    "Your potential is limitless, but it's up to you to take action and unlock it",
    "Every setback is an opportunity to learn, grow, and come back even stronger",
    "The greatest achievements start as simple ideas backed by action and determination",
    "Success comes when preparation meets opportunity, so always be ready to seize the moment",
    "Nothing worth having comes easy, but the effort you put in will be worth it in the end",
    "Your ability to stay disciplined and consistent will determine how far you go in life",
    "Keep learning, keep growing, and keep pushing forward, no matter what challenges arise",
    "The effort you put in today will bring results in ways you may not see right away",
    "Your success is a reflection of your habits, choices, and dedication over time",
    "Every day is an opportunity to improve, learn, and move one step closer to your dreams",
    "When you feel like giving up, remember why you started and push forward with determination",
    "The more effort you put in, the greater the rewards you will eventually receive",
    "Dreams don't work unless you do, so take action and make them a reality",
    "Success is not about being the best; it's about always striving to be better than yesterday",
    "The hardest part of success is staying consistent, even when motivation fades away",
    "Difficult moments are temporary, but the strength you gain from them lasts forever",
    "Believe in your vision, work hard, and success will follow in due time",
    "Every great accomplishment begins with the decision to try and keep going",
    "You are capable of achieving far more than you currently believe possible",
    "The key to long-term success is the ability to keep learning, adapting, and improving",
    "Your persistence will separate you from those who give up too soon",
    "If you stay focused and disciplined, success is only a matter of time",
    "Every action you take today is either bringing you closer to or further from your goals",
    "The struggle you are facing now is preparing you for the success ahead",
    "Results don't happen instantly, but with time, effort, and patience, they will appear",
    "Success is not a destination but a journey filled with lessons, growth, and progress",
    "Keep moving forward, because every small effort counts towards your bigger goals",
    "Doubt kills more dreams than failure ever will, so believe in yourself and take action",
    "Your willingness to keep going despite obstacles is what will make you successful",
    "Success is simply the result of consistent effort applied over a long period of time",
    "Stay patient and trust that your hard work will pay off at the right moment",
    "No dream is too big if you are willing to take small, consistent steps toward it",
    "Every skill you develop, every lesson you learn, will help shape your future success",
    "You don't have to see the entire path to take the first step toward your goals",
    "Focus on progress, not perfection, and keep pushing forward every single day",
    "The only limits in life are the ones you place on yourself, so think big and act boldly",
    "There is no failure—only lessons that help guide you toward something even better",
    "Your determination today will define the opportunities you have tomorrow",
    "Stay committed to your dreams, even when progress feels slow or uncertain",
    "The more you push yourself to grow, the more success you will experience",
    "No effort is ever wasted, because every experience contributes to your journey",
    "Surround yourself with positivity, stay consistent, and success will come",
    "Your growth is determined by the challenges you are willing to overcome",
    "Action is the foundation of success, so take steps forward every single day",
    "Every effort you put in today will bring rewards in the future, so keep going",
    "Stay dedicated, stay disciplined, and success will be within your reach",
    "No matter how slow your progress, you are still moving ahead every day",
    "Success is not just about talent; it's about the effort you put in consistently",
    "Your dreams are possible if you are willing to work hard and never give up",
    "The most important step is always the next one, so keep moving forward",
    "Everything you need to succeed is already within you—just take action",
    "Never underestimate the power of small actions repeated over time",
    "The path to success is built one step, one effort, one lesson at a time",
    "Effort and persistence always bring rewards, even if they take time to show up"
]

extreme_phrases = [
    "Success is the result of continuous effort discipline and learning from failures Every small step you take today brings you closer to your dreams Keep pushing forward and never let obstacles stop you from achieving what you truly desire in life Your potential is limitless",
    
    "Hard work patience and resilience will always lead you to great achievements Every challenge you overcome makes you stronger and more prepared for the future Stay focused trust your journey and remember that progress no matter how small is still progress Keep moving forward",
    
    "Your mindset and daily habits determine the future you create for yourself Success is not an overnight event but a result of consistent dedication and smart choices Keep improving keep growing and always believe in your ability to reach new levels of greatness",
    
    "Every great accomplishment starts with a simple decision to begin If you want to achieve something remarkable take the first step and never stop moving forward Challenges will arise but each one is an opportunity to grow learn and become stronger than before",
    
    "The key to success is not just having big dreams but also taking consistent action towards them Every day presents a new chance to improve and get closer to your goals Stay disciplined focused and determined because every effort you make today will shape your future",
    
    "Obstacles are not meant to stop you they are tests to see how much you truly want something When faced with difficulties push through and find a way to keep going Success comes to those who refuse to give up and keep striving for excellence no matter what",
    
    "Discipline and commitment are the foundation of lasting success No matter how talented or skilled you are it is your ability to remain consistent in your actions that will determine how far you go Keep pushing forward stay patient and trust that your efforts will pay off",
    
    "Great things take time and effort but every step forward no matter how small brings you closer to success Do not let temporary struggles discourage you Keep working hard learning and growing because every moment spent improving yourself will bring future rewards",
    
    "Your progress may seem slow but every effort counts towards your ultimate success The journey is just as important as the destination Stay focused on your growth and keep believing in yourself because with perseverance and dedication you can accomplish anything",
    
    "The best way to achieve success is to stay committed to continuous learning and self improvement Never settle for mediocrity keep challenging yourself to grow Every skill you develop today will open doors to even greater opportunities in the future",
    
    "Your dreams will only remain dreams unless you take action to make them a reality Consistent effort and a strong work ethic are the true keys to success Keep setting goals pushing forward and staying dedicated to your vision no matter what challenges arise",
    
    "Success does not happen overnight it is built on small daily actions and consistent effort Do not be discouraged by slow progress because every step forward brings you closer to your goals Stay patient stay focused and trust the process of growth and improvement",
    
    "Believe in your abilities and never allow fear or doubt to hold you back Every great success story begins with someone who dared to take a risk and work hard for what they wanted Stay determined keep learning and never stop striving for excellence",
    
    "Your dedication and consistency will set you apart from those who give up too soon Success is not about luck but about persistence and the willingness to keep improving every day Stay disciplined work hard and embrace the challenges that come your way",
    
    "The only way to truly fail is to stop trying Every setback is a lesson that prepares you for greater opportunities Keep pushing forward and using each challenge as a stepping stone to success Never stop believing in yourself and your ability to achieve great things",
    
    "No matter how difficult the journey may seem remember that every effort brings you one step closer to success Challenges build resilience and wisdom so embrace the process and keep moving forward with confidence your hard work will eventually pay off",
    
    "Success is not about talent alone it is about commitment and perseverance The people who achieve the most in life are those who refuse to quit despite setbacks Keep working hard stay positive and trust that your dedication will lead you to great achievements",
    
    "Big dreams require bold action and unwavering commitment Never let fear or doubt keep you from pursuing what you truly want in life Stay focused on your goals push through every obstacle and keep taking steps forward success is always within reach",
    
    "Your ability to stay consistent and disciplined will determine how far you go in life No dream is too big if you are willing to put in the effort and make daily progress toward achieving it Stay strong stay motivated and keep striving for greatness",
    
    "The most successful people are not those who never fail but those who never quit Learn from your mistakes adapt to challenges and keep pushing forward Every setback is simply a setup for a greater comeback so never stop working towards your dreams"
]
